---
abstract: 'observed, expected and variance counts, deviation and combinatorial tests, of Wald-type runs'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  List::AllUtils: 0.03
  Number::Misc: 1.0
  Statistics::Sequences: 0.11
  Statistics::Zed: 0.072
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Sequences-Runs
provides:
  Statistics::Sequences::Runs:
    file: lib/Statistics/Sequences/Runs.pm
    version: 0.11
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.11
